name: ApplSec bot

on:
  schedule:
    - cron: "0 * * * *"

jobs:
  setup:
    runs-on: macos-latest

    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install pytest
          pip install -r requirements.txt
      
      - name: Download stored_data.json
        uses: actions/download-artifact@v3
        with:
          name: stored_data_json
          path: src/stored_data.json

      - name: ApplSec bot
        env:
          TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
          TWITTER_API_KEY_SECRET: ${{ secrets.TWITTER_API_KEY_SECRET }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}

          TWITTER_TEST_API_KEY: ${{ secrets.TWITTER_TEST_API_KEY }}
          TWITTER_TEST_API_KEY_SECRET: ${{ secrets.TWITTER_TEST_API_KEY_SECRET }}
          TWITTER_TEST_ACCESS_TOKEN: ${{ secrets.TWITTER_TEST_ACCESS_TOKEN }}
          TWITTER_TEST_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_TEST_ACCESS_TOKEN_SECRET }}

          MASTODON_ACCESS_TOKEN: ${{ secrets.MASTODON_ACCESS_TOKEN }}

          MASTODON_TEST_ACCESS_TOKEN: ${{ secrets.MASTODON_TEST_ACCESS_TOKEN }}
        run: python main.py

      - name: Save stored_data.json
        uses: actions/upload-artifact@v3
        with:
          name: stored_data_json
          path: src/stored_data.json
          if-no-files-found: error
