name: pytest

on: [push, pull_request]

jobs:
  tests:
    name: Python 3.11

    runs-on: macos-latest

    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4.3.1
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install pytest
          pip install -r requirements.txt

      - name: pytest
        run: python -m pytest -vv
